import { useParams } from 'react-router-dom'
import { projects } from '../data/projects'
import { services } from '../data/services'
import { CTA, Label, PageHero, TextLink } from '../components/UI'
import ProjectMedia from '../features/ProjectMedia'
import SystemDiagram from '../features/SystemDiagram'
import NotFound from './NotFound'
export default function CaseStudy() {
  const { projectSlug } = useParams()
  const index = projects.findIndex(p => p.slug === projectSlug)
  if (index < 0) return <NotFound/>
  const project = projects[index], next = projects[(index+1)%projects.length]
  return <><PageHero dark label={`TNX / ${project.number} / CONCEPT STUDY`} title={project.name} description={project.summary}><TextLink to="/portfolio">Back to the portfolio</TextLink></PageHero><section className="case-visual dark" data-header-theme="dark"><div className="container"><ProjectMedia kind={project.preview}/><div className="case-meta">{[['Study','Technexa original concept'],['Context',project.sector],['Capability',project.capability],['Interface','React / TypeScript / CSS']].map(([k,v]) => <div key={k}><span className="mono">{k}</span><p>{v}</p></div>)}</div></div></section><section className="container section-space case-editorial"><Label>01 / PROJECT OVERVIEW</Label><div><h2>A system.<br/>Not a collection of screens.</h2><p className="body-large">{project.summary} This study evolves an original Technexa interface concept into a view of the broader system.</p></div></section><section className="container case-text-pair"><div><Label>02 / THE CHALLENGE</Label><h2>Where the work gets harder.</h2><p>{project.challenge}</p></div><div><Label>03 / OUR THINKING</Label><h2>Connect the right things.</h2><p>{project.thinking}</p></div></section><section className="dark section-space" data-header-theme="dark"><div className="container"><Label>04 / SYSTEM ARCHITECTURE</Label><h2 className="architecture-heading">The thinking behind the interface.</h2><SystemDiagram nodes={project.architecture} simulation={project.preview === 'flow'}/></div></section><section className="container section-space case-editorial"><Label>05 / THE PRODUCT EXPERIENCE</Label><div><h2>Complexity, made usable.</h2><p className="body-large">{project.experience}</p><div className="case-features">{project.features.map((f,i) => <div key={f}><span className="mono">0{i+1}</span>{f}</div>)}</div></div></section><section className="container case-interface"><Label>06 / INTERFACE EXPLORATION</Label><ProjectMedia kind={project.preview}/></section><section className="container section-space case-text-pair"><div><Label>07 / TECHNOLOGY</Label><h2>Built as an interface.</h2><p>The demonstrated interface is built with React, TypeScript and custom CSS. The system architecture is illustrative; production integrations, data storage and deployment are defined for each engagement.</p></div><div><Label>08 / WHAT THIS DEMONSTRATES</Label><h2>The value of connected thinking.</h2><p>{project.outcome}</p><CTA to={`/start-a-project?service=${encodeURIComponent(services.find(s => s.slug === project.service)!.name)}`}>Discuss a similar system</CTA></div></section><section className="next-project container"><Label>NEXT SYSTEM / {next.number}</Label><TextLink to={`/portfolio/${next.slug}`}>{next.name}</TextLink></section></>
}
