import { lazy, Suspense, useRef, useState } from 'react'
import { ArrowDown, ArrowUpRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import { BrandMark } from '../components/Brand'
import { CTA, Label, SectionHeader, TextLink } from '../components/UI'
import { services, principles } from '../data/services'
import PortfolioGallery from '../features/PortfolioGallery'
import SystemDiagram from '../features/SystemDiagram'
import ProjectMedia from '../features/ProjectMedia'
import Approach from '../sections/Approach'
import Technology from '../sections/Technology'
import useMotion from '../hooks/useMotion'
const Sculpture=lazy(()=>import('../components/Sculpture'))

export default function Home() {
  const [service,setService]=useState(0)
  const root=useRef<HTMLDivElement>(null)
  useMotion(root)
  return <div className="home2026" ref={root}>
    <section className="hero2026 dark" data-header-theme="dark"><div className="hero2026-grid" aria-hidden="true"/><div className="container">
      <div className="hero2026-topline"><Label>INDEPENDENT THINKING. CONNECTED ENGINEERING.</Label><span className="mono"><i className="status-dot"/> INDIA / WORKING EVERYWHERE</span></div>
      <div className="hero2026-main"><div className="hero2026-copy"><h1 className="hero2026-title"><span className="hero-line"><span>ENGINEERING</span></span><span className="hero-line"><span>YOUR NEXT</span></span><span className="hero-line"><span><em>ADVANTAGE.</em></span></span></h1><div className="hero-caption"><span className="mono">THINK BEYOND.<br/>BUILD WHAT’S NEXT.</span><p>Custom software. Intelligent automation.<br/>Connected systems that turn your ambition<br className="desktop-break"/> into an unfair advantage.</p></div><div className="hero2026-actions"><CTA light>Build your next advantage</CTA><TextLink to="/portfolio">Explore the portfolio</TextLink></div></div>
      <div className="engineered-object"><div className="object-topline mono"><span>TNX—01 / ORIGIN</span><span>LIVE 3D</span></div><div className="hero-object-frame"><div className="object-axis axis-x"/><div className="object-axis axis-y"/><div className="object-orbit orbit-a"/><div className="object-orbit orbit-b"/><div className="object-inner"><Suspense fallback={<BrandMark className="hero-fallback"/>}><Sculpture/></Suspense></div><span className="object-coordinate coord-a mono">X / 001</span><span className="object-coordinate coord-b mono">Y / 003</span><span className="object-cross">+</span></div><div className="object-bottomline mono"><span>THE SHAPE OF<br/>CONNECTED THINKING</span><ArrowUpRight size={28} strokeWidth={1}/></div></div></div>
      <div className="hero2026-bottom"><a href="#perspective" className="mono"><span className="scroll-disc"><ArrowDown size={15}/></span>SCROLL TO DISCOVER</a><span className="mono">STRATEGY<br/>DESIGN<br/>ENGINEERING</span><span className="hero-year mono">01 — ∞<small>MADE TO MOVE FORWARD</small></span></div>
    </div></section>
    <nav className="capabilities-ribbon" aria-label="Our capabilities"><div>{services.map(s=><Link to={`/expertise/${s.slug}`} key={s.slug}>{s.name}<span aria-hidden="true">↗</span></Link>)}</div></nav>
    <section id="perspective" className="perspective2026 container section-space"><div className="perspective-heading" data-reveal><Label>01 / BUILT FOR WHAT COMES NEXT</Label><span className="perspective-asterisk" aria-hidden="true">✳</span></div><div className="perspective-copy" data-reveal><h2>Ambition deserves<br/>better <span className="muted">infrastructure.</span></h2><div><p>Your next breakthrough isn’t another tool. It’s a better way for your people, processes and technology to work together. We design and engineer the systems that make it happen.</p><TextLink to="/about">Meet Technexa</TextLink></div></div><div className="perspective-rule" data-line/></section>
    <section className="selected-work2026 dark section-space" data-header-theme="dark"><div className="container"><div className="portfolio-section-heading" data-reveal><div><Label>02 / THE SYSTEM COLLECTION</Label><h2>IDEAS.<br/><span className="outline-type">ENGINEERED.</span></h2></div><div><p>A glimpse into the possibilities.<br/>Experience our original system concepts<br/>in an interactive, three-dimensional collection.</p><TextLink to="/portfolio">Enter the portfolio</TextLink></div></div><PortfolioGallery/></div></section>
    <section className="expertise-section container section-space"><div data-reveal><SectionHeader label="03 / THE EXPERTISE" title={<>Designed around you.<br/><span className="muted">Engineered to connect.</span></>} link="All capabilities" to="/expertise"/></div><div className="expertise-layout"><div className="expertise-list" role="tablist" aria-label="Explore capabilities">{services.map((s,i)=><button key={s.slug} role="tab" aria-selected={i===service} aria-controls="expertise-preview" id={`expertise-tab-${i}`} tabIndex={service===i?0:-1} onClick={()=>setService(i)} onKeyDown={e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();const next=(i+(e.key==='ArrowDown'?1:services.length-1))%services.length;setService(next);document.getElementById(`expertise-tab-${next}`)?.focus()}}}><span className="mono">{s.number}</span><span>{s.name}</span><ArrowUpRight size={23}/></button>)}</div><div className="expertise-detail" role="tabpanel" id="expertise-preview" aria-labelledby={`expertise-tab-${service}`}><div key={services[service].slug} className="expertise-visual" data-tilt><ProjectMedia kind={services[service].preview}/></div><div className="expertise-description"><h3>{services[service].short}</h3><p>{services[service].description}</p><TextLink to={`/expertise/${services[service].slug}`}>Explore {services[service].name.toLowerCase()}</TextLink></div></div></div></section>
    <section className="intelligence-section dark section-space" data-header-theme="dark"><div className="container"><div data-reveal><SectionHeader label="04 / INTELLIGENCE IN MOTION" title={<>A system that thinks.<br/><span className="muted">A team in control.</span></>} link="Explore agentic AI" to="/expertise/agentic-ai"/><p className="section-lead">Follow an enquiry from first contact to considered action. Run the simulation to see where intelligence connects—and where human judgement leads.</p></div><SystemDiagram simulation/></div></section>
    <section className="why-section container section-space"><div className="why-intro" data-reveal><Label>05 / A DIFFERENT KIND OF PARTNER</Label><h2>Sharp thinking.<br/>Serious engineering.<br/><span className="muted">Shared ambition.</span></h2><TextLink to="/about">Our way of thinking</TextLink><BrandMark className="principle-mark"/></div><div className="principle-list">{[principles[0],principles[1],principles[3]].map(([title,copy],i)=><div key={title} data-reveal><span className="mono">0{i+1}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></section>
    <div data-reveal><Approach/></div><Technology/>
    <section className="featured-insight container" data-reveal><div className="insight-art" aria-hidden="true"><div/><div/><div/><span className="mono">FIELD NOTES / 001<br/>SYSTEMS BEFORE SOFTWARE</span></div><div className="featured-insight-copy"><Label>08 / THINKING OUT LOUD</Label><span className="mono insight-meta">BUSINESS SYSTEMS / 4 MIN READ</span><h2><Link to="/insights/systems-before-software">Before you build software,<br/>understand the system.</Link></h2><p>The most valuable engineering work often happens before the first line of code.</p><TextLink to="/insights/systems-before-software">Read the perspective</TextLink></div></section>
  </div>
}
